### PR TITLE
[WiP] EEC merge

### PR DESCRIPTION
**Pull request by SebGue**
This is a work in progress PR to add some features to Electrical, LUT and EEC classes.

### CODE REVIEW

**Comment by SebGue** [comment]
Hello @EmileDvs 

for the LUT's there are some methods with 'store result for next call'. I think this could be an issue if one rerun a simulation with changed input parameters. This might likely happen e.g. in some future GUI. 
A solution could be to move e.g. 'Phi_dqh_mean' to XOutput.output_dict as a datakeeper. But the output_dict seems also not to be cleared a the beginning of a simulation. 
What do you think? 

Best regards, Sebastian

**Comment by EmileDvs** [comment]
Hello @SebGue,

Thanks for the commits, I am going to review all the modifications in the next days. Just a quick question before answering yours, the aim of this PR is to merge LUT/xLUT, LUTdq/xLUTdq, EEC/EECx, EEC_PMSM/EEC_PMSMx objects and not to duplicate them, is it right ?

Concerning your question, I saw two interests in calculating all EEC quantities through LUT getters (such as "Phi_dqh_mean") and temporarily store intermediate calculation in LUT (such as interpolant function):

- the getters enable to only save raw data in LUT (mainly Phi_wind) and calculate all the derived quantities (such as "Phi_dqh_mean", "Phi_dqh_mag" etc.) only when there are needed and also to reduce a bit the LUT size. This is why I didn't implement datakeepers although it would clearly have done the job. We can still store everything in the XOutput (Phi_wind/Phi_dqh_mean/Phi_dqh_mag etc.).
- the temporary store can save calculation time if some derived quantities are requested for many operating points in a row (for example when calculating control strategy we don't want to recalculate interpolant function for each operating point). 
 
However, I totally agree with the fact that intermediate quantities such as interpolant function shoudn't be saved in the LUT object so that it is always at None when loading the object. That way if Phi_wind has changed then all intermediate quantities are recalculated accounting for new changes, and then temporarily stored for further used.

Best regards,
Emile

**Comment by EmileDvs** [comment]
In the meanwhile, I did further changes to continue to improve EEC/LUT/Electrical workflows on my side, mainly to improve PWM calculation and better integrate EEC parameter calculation using LUT as you suggested a couple of weeks ago. 

Once we'll have merged this PR I will spend some time to integrate my changes in a next branch so the circle is complete :)

Best regards,
Emile

**Comment by SebGue** [comment]
Hello @EmileDvs ,

I hope you haven't started your review yet, since this PR is work in progress. I will tell you when I'm finished.
As you guessed, the x classes are for merge only. I don't want to duplicate any of the classes. I just found it easier to keep the originals for now.

For your changes on EEC, ... we could also do it the other way round, since you may be faster with your PR. I.e. you merge your changes to the EEC_rework and I adapt my PR and solve possible conflicts. 

For the temporary storeage of values, I think I will keep it for now and we may discuss it in a dedicated issue?!
There are different things to consider in my opinion. E.g. it is difficult to detect if Phi_wind has changed. The question should be, if we introduce proper output cleaning as the init of a simulation run to ensure that there are no old invalid data in the output.

Best regrads,
Sebastian

**Comment by EmileDvs** [comment]
Hello @SebGue,

I just had a quick look to check the new files, I'll wait for your go-ahead.

No problem to merge my changes in this PR, I'll try do to it by next week.

Best regards,
Emile

**Comment by EmileDvs** [comment]
Hello @SebGue,

For your information I have started a pull requested to pyleecan master with the latest changes I did concerning Electrical/EEC/Input classes (#481).

The validation tests still need to be corrected before merging #481 into the master, however you can already start to have a look at it and then merging this PR to EEC_rework.

Best regards,
Emile

**Comment by EmileDvs** [comment]
Hello @SebGue,

I agree with you, I think there is no problem to get Phi_wind value from XOutput every time it is needed.

Best regards,
Emile

**Pull request closed without merging**
